ashishb/adb-enhanced

README.md, src/adbe.py, tests/adbe_tests.py
=> List backup enabled apps

.circleci/config.yml, .travis.yml, release/release_new_build.sh, src/adbe.py, tests/adbe_tests.py
Addresses https://github.com/ashishb/adb-enhanced/issues/17
=> Backup extractor

src/adbe.py, tests/adbe_tests.py
So, that I can stop maintaining Python 2 support in 2019
=> Warn about upcoming Python 2 deprecation

src/output_helper.py, tests/adbe_tests.py
Don't output colors on non-interactive terminals
=> Output helper improvement

src/adbe.py
=> Simplify rotation code

src/adbe.py
=> Remove auto-tap during backup

.circleci/config.yml, .travis.yml, release/release_new_build.sh
This test is already there on Travis. Add this to Circle CI as well.
=> Add setup testing to Circle CI

.travis.yml
Add job labels for Travis jobs
=> Add job labels for Travis jobs

.circleci/config.yml, .travis.yml, src/adb_helper.py, src/adbe.py, tests/lint_check_python2.sh, tests/lint_check_python3.sh
Add Lint checking and fix lint issues
=> Add Lint checking and fix lint issues

src/adbe.py
=> Make backup tar file name optional

src/adbe.py
Try to invoke airplane mode change broadcast intent with root since on
newer versions of Android, it cannot be invoked by the shell user.
=> Improve airplane mode

tests/adbe_tests.py, tests/lint_check_python2.sh, tests/lint_check_python3.sh
=> Add more testing

.travis.yml
Travis CI should test push and not PR. Otherwise, it runs twice for
every pull request.
=> Reduce Travis redundancy

README.md
=> Cleanup badges in README.md

release/setup.py, src/adb_enhanced.py, src/main.py, tests/adbe_tests.py, tests/lint_check_python2.sh, tests/lint_check_python3.sh
Reduce functionality in main.py
Logic should exist in adb_enhanced.py
=> More code cleanup

.travis.yml, tests/adbe_tests.py, tests/conftest.py
Test a full installation by installing the python binary and running tests against it
=> Test real installation

.travis.yml
=> Cleanup Travis.yml

.travis.yml, bors.toml
Add support for https://github.com/bors-ng/bors-ng
=> Add Bors-ng

src/adb_enhanced.py, src/adb_helper.py
execute_adb_command2 and execute_adb_shell_command2 will return the
success/failure code and stderr of the command
=> Add new methods which return whether command failed or not

src/adb_enhanced.py, src/adb_helper.py
=> Move getprop command to adb_helper.py

src/adb_enhanced.py, src/adb_helper.py, src/asyncio_helper.py, src/main.py, src/output_helper.py, tests/adbe_tests.py, tests/lint_check_python3.sh
Cleanup several lint issues and improve coed quality
=> Cleanup several lint issues

tests/adbe_tests.py
Clean up testing. Test some functions, which were being tested together, separately.
=> Clean up testing - test separately

src/adb_enhanced.py, src/main.py
As recommeneded in https://github.com/ashishb/adb-enhanced/issues/80
Show value of settings before and after the operation. For example,
```
$ python3 src/main.py show-taps on
Show user taps state changed from "off" -> "on"
$ python3 src/main.py show-taps on
Show user taps state unchanged (on)
$ python3 src/main.py show-taps off
Show user taps state changed from "on" -> "off"
```
I have implemented it for the following settings.
1. adbe [options] mobile-data (on | off)
2. adbe [options] battery saver (on | off) - done
3. adbe [options] mobile-data saver (on | off)
4. adbe [options] dont-keep-activities (on | off)
5. adbe [options] stay-awake-while-charging (on | off)
6. adbe [options] show-taps (on | off)
I have not yet implemented it for the following settings
1. adbe [options] gfx (on | …
=> Show values of settings

.github/workflows/lint_python2.yml, .github/workflows/lint_python3.yml, .github/workflows/main.yml
Also, fix indentation in existing actions
=> Add GitHub actions for code linting

.github/workflows/adbe-installtests-python3.yml
1. Test adb installation
2. Test more API versions of Android
3. Added once a week automated testing on Schedule
=> Improvement to testing

.github/workflows/adbe-installtests-python3.yml
com.android.contacts package is not debuggable on it and the test fails
=> Don't test on API 26

adbe/adb_enhanced.py, adbe/main.py
Addresses https://github.com/ashishb/adb-enhanced/issues/109
=> Add command to enable/disable Wi-Fi

Makefile, adbe/adb_enhanced.py, adbe/adb_helper.py, adbe/main.py, tests/adbe_tests.py
- Address several lint issues
- remove Python-2 specific code
=> More lint cleanup

README.md, adbe/adb_enhanced.py, adbe/adb_helper.py, adbe/main.py, docs/README.rst, tests/adbe_tests.py
Screen toggle feature for #76 
Tested on Android 11 @ Pixel 4 and Android 6.0.1 @ Nexus 7 2013
=> Turn on/off screen by adbe screen command

README.md, adbe/adb_enhanced.py, adbe/main.py
- Add support for top alarms : 
```
$ adbe alarm top
android
Action: TIME_TICK
Running time: +4s300ms
Number of device woke up: 0
Number of alarms: 1973
User ID: 1000
android
Action: com.android.server.action.NETWORK_STATS_POLL
Running time: +3s537ms
Number of device woke up: 0
Number of alarms: 66
User ID: 1000
android
Action: WifiConnectivityManager Schedule Periodic Scan Timer
Running time: +770ms
Number of device woke up: 692
Number of alarms: 692
User ID: 1000
android
Action: WifiConnectivityManager Schedule Watchdog Timer
Running time: +154ms
Number of device woke up: 98
Number of alarms: 98
User ID: 1000
com.android.providers.calendar
Action: com.android.providers.calendar.intent.CalendarProvider2
Running time: +92ms
Number of device woke up: 6
Number of alarms: 6
User ID: u0a42 …
```
=> Issue 120 

adbe/adb_enhanced.py
In some cases, the command 'pm list packages' will not list all enabled third party packages (same for -e and -s). 
https://stackoverflow.com/questions/63416599/adb-shell-pm-list-packages-missing-some-packages
=> Replace 'pm list packages' with 'dumpsys package'

adbe/adb_enhanced.py, adbe/main.py, tests/adbe_tests.py
Reverts ashishb/adb-enhanced#137 due to the failure https://github.com/ashishb/adb-enhanced/runs/1692399281?check_suite_focus=true
=> Revert "Wireless debug fix"

README.md, adbe/adb_enhanced.py, adbe/main.py
Changing command `uninstall <package>` with shell command `pm uninstall --user 0 <package>` using user 0 privileges
=> Uninstall using first user

adbe/adb_enhanced.py, adbe/main.py
Split `list_non_system_app()`:
`get_list_non_system_app()`: return a list of installed third party packages
`print_list_non_system_app()`: print list of installed  third party packages
=> Split list non system app

adbe/adb_enhanced.py
Fixes https://github.com/ashishb/adb-enhanced/issues/161
=> Fix dark mode commands

.github/workflows/adbe-installtests.yml, .github/workflows/adbe-unittests-api16.yml, .github/workflows/adbe-unittests-api21.yml, .github/workflows/adbe-unittests-api22.yml, .github/workflows/adbe-unittests-api23.yml, .github/workflows/adbe-unittests-api24.yml, .github/workflows/adbe-unittests-api25.yml, .github/workflows/adbe-unittests-api26.yml, .github/workflows/adbe-unittests-api27.yml, .github/workflows/adbe-unittests-api28.yml, .github/workflows/adbe-unittests-api29.yml, .github/workflows/adbe-unittests.yml, .github/workflows/install-adbe.yml, .github/workflows/lint-python.yml
Ref: https://github.com/actions/checkout
=> Upgrade checkout@v2 -> checkout@v3

.github/workflows/adbe-unittests-api21.yml, .github/workflows/adbe-unittests-api22.yml, .github/workflows/adbe-unittests-api23.yml, .github/workflows/adbe-unittests-api24.yml, .github/workflows/adbe-unittests-api25.yml, .github/workflows/adbe-unittests-api26.yml, .github/workflows/adbe-unittests-api27.yml, .github/workflows/adbe-unittests-api28.yml, .github/workflows/adbe-unittests-api29.yml
Run the job whenever the CI definition YAML file changes
=> Add more path filter to GitHub CI jobs that are on schedule

.github/workflows/adbe-unittests-api16.yml, .github/workflows/adbe-unittests-api21.yml, .github/workflows/adbe-unittests-api22.yml, .github/workflows/adbe-unittests-api23.yml, .github/workflows/adbe-unittests-api24.yml, .github/workflows/adbe-unittests-api25.yml, .github/workflows/adbe-unittests-api26.yml, .github/workflows/adbe-unittests-api27.yml, .github/workflows/adbe-unittests-api28.yml, .github/workflows/adbe-unittests-api29.yml
Before caching, it takes 6 mins 38 seconds https://github.com/ashishb/adb-enhanced/actions/runs/4310868226 After caching, it takes 3 mins and 58 seconds https://github.com/ashishb/adb-enhanced/actions/runs/4310958302
=> Add AVD caching to all Android tests

tests/adbe_tests.py
- This should speed up the tests
- Only test code has been changed
=> Cache SDK version for testing

adbe/main.py
- Order all commands alphabetically
- Add more helpful description to the tool
=> Minor improvements to CLI

adbe/adb_enhanced.py
- Add type hints for some functions
- No functionality change
=> Add type hints

adbe/main.py
Remove a big clunky if-else ladder with a dictionary
=> Simplify code in main.py

.github/workflows/adbe-unittests-api33.yml, adbe/adb_enhanced.py, adbe/main.py, tests/adbe_tests.py
This permission was added in API 33
https://developer.android.com/develop/ui/views/notifications/notification-permission
=> Add `notifications` permission group handling

pyproject.toml, uv.lock
They will be used in CI in a follow-on PR
=> chore: add `ruff` and `autoflake` as dev dependencies for code quality

adbe/adb_enhanced.py, adbe/main.py
=> chore: fix imports using `isort`

tests/adbe_tests.py, tests/conftest.py
Eventually, all code will use double quotes
=> chore: use double quotes in test files

adbe/adb_enhanced.py, adbe/asyncio_helper.py
Ref: https://docs.astral.sh/ruff/rules/manual-list-copy/
=> chore: fix PERF402

adbe/adb_enhanced.py, tests/adbe_tests.py
Ref: https://docs.astral.sh/ruff/rules/#flake8-return-ret
=> chore: fix `RET` related issues

adbe/adb_enhanced.py, tests/adbe_tests.py
Ref: https://docs.astral.sh/ruff/rules/#flake8-simplify-sim
=> chore: improve codebase using `SIM`

tests/adbe_tests.py, tests/conftest.py
Ref: https://docs.astral.sh/ruff/rules/#pyupgrade-up
=> chore: fix test code using `UP` rule

adbe/adb_enhanced.py, adbe/adb_helper.py, adbe/main.py
Ref: https://docs.astral.sh/ruff/rules/#pyupgrade-up
=> chore: fix code using `UP` rule

adbe/adb_enhanced.py, adbe/adb_helper.py, adbe/main.py, adbe/output_helper.py
Ref: https://docs.astral.sh/ruff/rules/boolean-default-value-positional-argument/
=> chore: fix a lot of `fbt` issues

tests/adbe_tests.py, tests/conftest.py
Ref: https://docs.astral.sh/ruff/rules/#flake8-annotations-ann
=> chore: add types in test code

adbe/adb_enhanced.py, adbe/adb_helper.py, adbe/asyncio_helper.py, adbe/main.py
Modernize more code with types
=> chore: add types in more code

Makefile, adbe/adb_enhanced.py, adbe/adb_helper.py
Also, fix screen recording which was broken
=> chore: major clean up in code base related to adb command execution
