ashishb/adb-enhanced

tests/adbe_tests.py

Remove "rm -rf /data/local/tmp" this would happen in Python 3 test_misc test and then Python 2 test would fail to create the file in that directory. As a precaution, I am creating the directory as well in the test_move command

Add more logging in test_file_move1

---

src/adbe.py

Its required to reduce the cognitive overload. The developer can type
adbe for install and uninstall as well.

Add install/uninstall option

---

.circleci/config.yml
tests/adbe_tests.py

Add API 16 and 24 testing to Circle CI. All tests enabled on API 16. Only doze testing enabled on API 24. I want to do permissions testing on API 24 but Circle CI hangs on that. I will address that some other day.

Add full API 16 testing to Circle CI and test doze on API 24

---

.circleci/config.yml
src/adbe.py
tests/adbe_tests.py

1. It seems `settings` tool is only available on API 19 and above, so,
error if it is used below that.
2. Add a single helper method to display a message whenever the user
tries to invoke commands not supported on an older device version.

Fix settings related commands

---

src/adbe.py

Add checks to ensure that apksigner.jar and abe.jar are present and we
are failing mysteriously due to corrupted installation.

Add more checks to ensure jar files are present

---

src/adbe.py

Require password for backup since on devices  with security lock
enabled, a backup has to be password-protected

Password for backup

---

src/adb_enhanced.py
src/adb_helper.py
tests/adbe_tests.py

The approach to handle file related commands was clumsy. I was stiching
a single command with both "run-as" and "root" prefixes creating three
versions which were combined and passed to adb shell as a single
command. This required convluted escaping as well.
I replaced that with a simpler approach where the caller passes a
filepath to a single method which decides whether to run this command
with run-as or even try root. It will then run the three versions one
by one and stops on the first success. This eliminates a lot of clumsy
logging as well.
Also, fixed a big in push file where the temporary file was being
deleted before being copied to its final location.

Cleanup run-as and root

---

.travis.yml
requirements.txt

Pytest 4.6.4 works. Freeze that for testing on Travis CI. The newer version of pytest seems
to be incompatible with Python 3.5 and fails on Travis CI. I cannot
upgrade Python version on Travis CI since it seems 3.5 is the latest
version available for `android` docker images.
Failure:
https://travis-ci.org/ashishb/adb-enhanced/builds/551900301

Freeze Pytest version to 4.6.4

---

.travis.yml
requirements.txt
tests/adbe_tests.py

As recommended at
https://github.com/pytest-dev/pytest/issues/5654#issuecomment-514526483,
try using Python3 without sudo to use the virtualenv version and not the
system's Python on Circle CI.
Further note: https://docs.travis-ci.com/user/languages/python/#travis-ci-uses-isolated-virtualenvs

Don't use sudo with python3

---

.github/workflows/adbe-unittests-python3-old.yml

Now, that the GitHub Actions library which we rely upon supports that
https://github.com/ReactiveCircus/android-emulator-runner/pull/28

Test API 16

---

.github/workflows/adbe-unittests-python3-api21.yml
.github/workflows/adbe-unittests-python3-api22.yml
.github/workflows/adbe-unittests-python3-api23.yml
.github/workflows/adbe-unittests-python3-api24.yml
.github/workflows/adbe-unittests-python3-api25.yml
.github/workflows/adbe-unittests-python3-api26.yml
.github/workflows/adbe-unittests-python3-api27.yml
.github/workflows/adbe-unittests-python3-api28.yml
.github/workflows/adbe-unittests-python3-api29.yml

The combined test would fail due to one of the tests components failing
and that would cause a lot of trouble. So, best is to separate tests
into different, so that, they can be run individually.

Add individual tests for Api 22 to 29

---

adbe/adb_enhanced.py

Uninstall automatic fallback to first user in case the regular uninstall command fails.

Uninstall automatic fallback to first user

---

adbe/adb_enhanced.py
adbe/main.py

Earlier, quite a few functions that used to print state modifications
were reading the previous/next state manually
Now, automate that code with a python decorator. This reduces the code
as well makes main.py smaller.
Long term, I want to reduce logic in main.py, so that, `docopt` argument
parsing library can be replaced by a better library.

Code cleanup related to state change

---

setup.cfg

Replace `description-file` -> `description_file` in `setup.cfg`
```
Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
```

Replace `description-file` -> `description_file`

---

README.md
adbe/adb_enhanced.py
adbe/main.py
tests/adbe_tests.py

Clone of https://github.com/ashishb/adb-enhanced/pull/167 with a fix to the testing code.
Original PR message:
I've tested it in Android 10 (API 29), Android 11 (API 30), and Android 12 (API 32).
For versions lower than API 29 the command doesn't work, and we have to use `location_providers_allowed`. But it gets complicated because we have 3 modes: battery saving, phone only, and high accuracy. And the command doesn't seem to be reliable. I leave it for another PR.
This closes #166

Add location

---

setup.py

Increase minimum version requirement from 3.4 -> 3.6
https://devguide.python.org/versions/

Increase minimum version requirement to Python 3.6

---

.github/workflows/adbe-unittests-api16.yml
.github/workflows/adbe-unittests-api21.yml
.github/workflows/adbe-unittests-api22.yml
.github/workflows/adbe-unittests-api23.yml
.github/workflows/adbe-unittests-api24.yml
.github/workflows/adbe-unittests-api25.yml
.github/workflows/adbe-unittests-api26.yml
.github/workflows/adbe-unittests-api27.yml
.github/workflows/adbe-unittests-api28.yml
.github/workflows/adbe-unittests-api29.yml
.github/workflows/adbe-unittests-api30.yml
.github/workflows/adbe-unittests-api31.yml
.github/workflows/adbe-unittests-api32.yml
.github/workflows/adbe-unittests-api33.yml
.github/workflows/adbe-unittests-api34.yml
.github/workflows/adbe-unittests.yml
.github/workflows/install-adb-enhanced-from-homebrew.yml

As per
https://github.com/ReactiveCircus/android-emulator-runner?tab=readme-ov-file#running-hardware-accelerated-emulators-on-linux-runners, these are faster.
In our case, the speed-up seems to be 2-3X faster executions.

ci: switch from `macos-latest` -> `ubuntu-latest` + KVM

---

adbe/adb_enhanced.py
adbe/main.py
tests/adbe_tests.py

A bit more information here:
https://developer.android.com/tools/adb#am

Implement setting and clearing debug app

---

.github/workflows/adbe-installtests.yml
.github/workflows/adbe-unittests-api16.yml
.github/workflows/adbe-unittests-api21.yml
.github/workflows/adbe-unittests-api22.yml
.github/workflows/adbe-unittests-api23.yml
.github/workflows/adbe-unittests-api24.yml
.github/workflows/adbe-unittests-api25.yml
.github/workflows/adbe-unittests-api28.yml
.github/workflows/adbe-unittests-api29.yml
.github/workflows/adbe-unittests-api30.yml

`gradle/gradle-build-action@v3` -> `gradle/actions/setup-gradle@v3`
Ref: https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#the-action-gradlegradle-build-action-has-been-replaced-by-gradleactionssetup-gradle

ci: replace deprecate Gradle action

---

adbe/adb_enhanced.py

```
flake8 adbe --count --ignore=F401,E126,E501,W504 --show-source --statistics
adbe/adb_enhanced.py:643:9: F824 `global screen_record_file_path_on_device` is unused: name is never assigned in scope
global screen_record_file_path_on_device
^
1     F824 `global screen_record_file_path_on_device` is unused: name is never assigned in scope
1
make: *** [Makefile:43: lint_python3] Error 1
```

fix: fix a lint issue

---

.github/workflows/adbe-unittests.yml
.github/workflows/install-adb-enhanced-from-pip.yml
.github/workflows/lint-python.yaml

Reduce parallelism to fail early and save CI time

ci: run CI tests on Python 3.12

---

.github/workflows/adbe-installtests.yml
.github/workflows/adbe-unittests-api16.yml
.github/workflows/adbe-unittests-api21.yml
.github/workflows/adbe-unittests-api22.yml
.github/workflows/adbe-unittests-api23.yml
.github/workflows/adbe-unittests-api24.yml
.github/workflows/adbe-unittests-api25.yml
.github/workflows/adbe-unittests-api26.yml
.github/workflows/adbe-unittests-api27.yml
.github/workflows/adbe-unittests-api28.yml
.github/workflows/adbe-unittests-api29.yml
.github/workflows/adbe-unittests-api30.yml
.github/workflows/adbe-unittests-api31.yml
.github/workflows/adbe-unittests-api32.yml
.github/workflows/adbe-unittests-api33.yml
.github/workflows/adbe-unittests-api34.yml
.github/workflows/adbe-unittests.yml
.github/workflows/lint-python.yaml
Makefile

There is no Python 2 anymore.
And hopefully, there won't be Python 4.

chore: `test_python3` -> `test_python` and `lint_python3` -> `lint_python`

---

adbe/adb_enhanced.py
adbe/main.py
tests/adbe_tests.py

Ref: https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth

chore: use `pathlib.Path` everywhere

---

adbe/adb_enhanced.py
uv.lock

xapk files are zip files containing apk files
This adds ability to install them using the same `install` command.
Ref: https://github.com/ashishb/adb-enhanced/issues/303

feat: add ability install `xapk` files

---

Makefile
adbe/adb_enhanced.py
pyproject.toml
uv.lock

- Eliminate `flake8`, `autopep8` and `pylint`
- `ruff` is faster

chore: migrate to `ruff`
